baseURL                          = "/"  # Your domain name. Must end with "/"
theme                            = "introduction"
DefaultContentLanguage           = "en"                    # Default language for multilingual sites
# disqusshortname                 = ""                       # https://gohugo.io/content-management/comments
googleAnalytics                 = "UA-161448619-1"                       # https://gohugo.io/templates/internal/#google-analytics

[params]
    themeStyle                   = "light"                 # Choose "light" or "dark"
    favicon                      = "/img/mathematics.png"          # Path to favicon file
    showRSSButton                = false                   # Show rss button in navigation
    fadeIn                       = true                    # Turn on/off the fade-in effect
    fadeInIndex                  = false                   # Turn on/off the fade-in effect on the index page even if fade-in was otherwise turned off
    dateFormat                   = "Jan 2, 2006"
    email                        = "amaya.nogales-gomez@i3s.unice.fr"   # E-mail address for contact section
    # customCSS                    = ["foo.css"]             # Include custom css files placed under assets/

    # Configure the home page
    [params.home]
        introHeight              = "fullheight"            # Input either "medium" or "large" or "fullheight"
        showLatest               = true                    # Show latest blog post summary
        showAllPosts             = false                   # Set true to list all posts on home page, or set false to link to separate blog list page
        numberOfProjectsToShow   = 4                       # Maximum number of projects to show on home page. Unset or comment out to show all projects

        localTime                = false                    # Show your current local time in contact section
        timeZone                 = "America/Los_Angeles"   # Your timezone as in the TZ* column of this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
        timeFormat               = "h:mm A"                # https://momentjs.com/docs/#/displaying/format/
    [params.projects]
        useTwoColumns            = false                   # Use a layout with two columns instead of three

    # Share buttons on blog post pages
    [params.share]
        twitter                  = false
        facebook                 = false
        googlePlus               = false
        pinterest                = false

    # Social icons appear in introduction and contact section. Add as many more as you like.
    # Icon pack "fab" includes social network icons, see: https://fontawesome.com/icons?d=gallery&s=brands&m=free
    # Icon pack "fas" includes solid style icons, see: https://fontawesome.com/icons?d=gallery&s=solid&m=free
    [[params.social]]
        url   = "https://scholar.google.com/citations?user=VlbI1uIAAAAJ&amp;hl=es"
        icon  = "graduation-cap" # icon name without the 'fa-'
        icon_pack = "fas"
    [[params.social]]
        url   = "https://www.linkedin.com/in/amaya-nogales-gomez"
        icon  = "linkedin-in" # icon name without the 'fa-'
        icon_pack = "fab"
    [[params.social]]
        url = "mailto:amaya.nogales-gomez@i3s.unice.fr"  # For a direct email link, use "mailto:test@example.org".
        icon = "paper-plane" # icon name without the 'fa-'
        icon_pack = "fas"


# If you don't want to use the default menu, you can define one by yourself
# [[menu.main]]
#     name    = "About"
#     url     = "/"
#     weight  = 4
# [[menu.main]]
#     name    = "Contact"
#     url     = "/Contact"
#     weight  = 5
# [[menu.main]]
#     name    = "Research"
#     url     = "/content/en/home/"
#     weight  = 6
#[[menu.main]]
#    name = "CV"
#    url = "/pdf/AThesis.pdf"
#    weight = 100

# We only use tag as a taxonomies
# You can add more by yourself
[taxonomies]
  tag = "tags"

[languages]
    [languages.en]
        languageName     = "English"
        languageCode     = "en-us"
        contentDir       = "content/en"
        weight           = 0
        title            = "Amaya Nogales Gómez"
        [languages.en.params]
            description  = "Website Description"   # Max 160 characters show in search results
#            footerText   = "."                      # Text to override default footer text (markdown allowed)

#    [languages.es]
#        languageName     = "Español"
#        languageCode     = "es"
#        contentDir       = "content/es"
#        weight           = 1
#        title            = "Introducción"
#        [languages.es.params]
#            description  = "Descripcion del sitio web"
            # footerText   = ""

    
